AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  firstlambda

  Sample SAM Template for firstlambda

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: data_types.cold_start_basic
      Runtime: python3.8
      Architectures:
        - x86_64
  # DataTypes:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: hello_world/
  #     Handler: data_types.simple_types
  #     Runtime: python3.8
  #     Architectures:
  #       - x86_64
  # ListTypes:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: hello_world/
  #     Handler: data_types.list_types
  #     Runtime: python3.8
  #     Architectures:
  #       - x86_64
  # DictTypes:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: hello_world/
  #     Handler: data_types.dict_types
  #     Runtime: python3.8
  #     Architectures:
  #       - x86_64
  # ContextObject:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: hello_world/
  #     Handler: data_types.context_object
  #     Runtime: python3.8
  #     Architectures:
  #       - x86_64
  #     Timeout: 4
  #     Environment:
  #       Variables:
  #         ROOT_URL: http://localhost
  #         DB_NAME: test
